using Fluenzi.Mattermost.Enums;

namespace Fluenzi.Mattermost.Constants;

public static class WebSocketEventNames
{
    public const string Hello = "hello";
    public const string Posted = "posted";
    public const string PostEdited = "post_edited";
    public const string PostDeleted = "post_deleted";
    public const string PostUnread = "post_unread";
    public const string EphemeralMessage = "ephemeral_message";
    public const string PostAcknowledgementAdded = "post_acknowledgement_added";
    public const string PostAcknowledgementRemoved = "post_acknowledgement_removed";
    public const string ReactionAdded = "reaction_added";
    public const string ReactionRemoved = "reaction_removed";
    public const string ChannelCreated = "channel_created";
    public const string ChannelUpdated = "channel_updated";
    public const string ChannelDeleted = "channel_deleted";
    public const string ChannelConverted = "channel_converted";
    public const string ChannelViewed = "channel_viewed";
    public const string ChannelMemberUpdated = "channel_member_updated";
    public const string ChannelSchemeUpdated = "channel_scheme_updated";
    public const string ChannelRestored = "channel_restored";
    public const string DirectAdded = "direct_added";
    public const string GroupAdded = "group_added";
    public const string MultipleChannelsViewed = "multiple_channels_viewed";
    public const string NewUser = "new_user";
    public const string UserAdded = "added_to_channel";
    public const string UserUpdated = "user_updated";
    public const string UserRemoved = "user_removed";
    public const string UserRoleUpdated = "user_role_updated";
    public const string MemberRoleUpdated = "memberrole_updated";
    public const string UserActivationStatusChange = "user_activation_status_change";
    public const string Typing = "typing";
    public const string StatusChange = "status_change";
    public const string PresenceIndicator = "presence_indicator";
    public const string AddedToTeam = "added_to_team";
    public const string LeaveTeam = "leave_team";
    public const string UpdateTeam = "update_team";
    public const string DeleteTeam = "delete_team";
    public const string RestoreTeam = "restore_team";
    public const string UpdateTeamScheme = "update_team_scheme";
    public const string ThreadUpdated = "thread_updated";
    public const string ThreadFollowChanged = "thread_follow_changed";
    public const string ThreadReadChanged = "thread_read_changed";
    public const string PreferencesChanged = "preferences_changed";
    public const string PreferencesDeleted = "preferences_deleted";
    public const string EmojiAdded = "emoji_added";
    public const string SidebarCategoryCreated = "sidebar_category_created";
    public const string SidebarCategoryUpdated = "sidebar_category_updated";
    public const string SidebarCategoryDeleted = "sidebar_category_deleted";
    public const string SidebarCategoryOrderUpdated = "sidebar_category_order_updated";
    public const string RoleUpdated = "role_updated";
    public const string PluginStatusesChanged = "plugin_statuses_changed";
    public const string PluginEnabled = "plugin_enabled";
    public const string PluginDisabled = "plugin_disabled";
    public const string LicenseChanged = "license_changed";
    public const string ConfigChanged = "config_changed";
    public const string OpenDialog = "open_dialog";
    public const string CloseDialog = "close_dialog";
    public const string DraftCreated = "draft_created";
    public const string DraftUpdated = "draft_updated";
    public const string DraftDeleted = "draft_deleted";
    public const string CallStarted = "call_started";
    public const string CallEnded = "call_ended";
    public const string CallUserJoined = "call_user_joined";
    public const string CallUserLeft = "call_user_left";
    public const string CallScreenOn = "call_screen_on";
    public const string CallScreenOff = "call_screen_off";
    public const string CallChannelState = "call_channel_state";
    public const string ReceivedGroup = "received_group";
    public const string ReceivedGroupAssociatedToTeam = "received_group_associated_to_team";
    public const string ReceivedGroupNotAssociatedToTeam = "received_group_not_associated_to_team";
    public const string ReceivedGroupAssociatedToChannel = "received_group_associated_to_channel";
    public const string ReceivedGroupNotAssociatedToChannel = "received_group_not_associated_to_channel";
    public const string GroupMemberAdd = "group_member_add";
    public const string GroupMemberDelete = "group_member_delete";
    public const string CloudPaymentStatusUpdated = "cloud_payment_status_updated";
    public const string CloudSubscriptionChanged = "cloud_subscription_changed";
    public const string ChannelBookmarkCreated = "channel_bookmark_created";
    public const string ChannelBookmarkUpdated = "channel_bookmark_updated";
    public const string ChannelBookmarkDeleted = "channel_bookmark_deleted";
    public const string ChannelBookmarkSorted = "channel_bookmark_sorted";
    public const string ScheduledPostCreated = "scheduled_post_created";
    public const string ScheduledPostUpdated = "scheduled_post_updated";
    public const string ScheduledPostDeleted = "scheduled_post_deleted";
    public const string GuestRequested = "guest_requested";
    public const string PostTranslationUpdated = "post_translation_updated";
    public const string ShowToast = "show_toast";
    public const string WebRTC = "webrtc";

    public static readonly IReadOnlyDictionary<string, WebSocketEventType> NameToType = new Dictionary<string, WebSocketEventType>
    {
        [Hello] = WebSocketEventType.Hello,
        [Posted] = WebSocketEventType.Posted,
        [PostEdited] = WebSocketEventType.PostEdited,
        [PostDeleted] = WebSocketEventType.PostDeleted,
        [PostUnread] = WebSocketEventType.PostUnread,
        [EphemeralMessage] = WebSocketEventType.EphemeralMessage,
        [PostAcknowledgementAdded] = WebSocketEventType.PostAcknowledgementAdded,
        [PostAcknowledgementRemoved] = WebSocketEventType.PostAcknowledgementRemoved,
        [ReactionAdded] = WebSocketEventType.ReactionAdded,
        [ReactionRemoved] = WebSocketEventType.ReactionRemoved,
        [ChannelCreated] = WebSocketEventType.ChannelCreated,
        [ChannelUpdated] = WebSocketEventType.ChannelUpdated,
        [ChannelDeleted] = WebSocketEventType.ChannelDeleted,
        [ChannelConverted] = WebSocketEventType.ChannelConverted,
        [ChannelViewed] = WebSocketEventType.ChannelViewed,
        [ChannelMemberUpdated] = WebSocketEventType.ChannelMemberUpdated,
        [ChannelSchemeUpdated] = WebSocketEventType.ChannelSchemeUpdated,
        [ChannelRestored] = WebSocketEventType.ChannelRestored,
        [DirectAdded] = WebSocketEventType.DirectAdded,
        [GroupAdded] = WebSocketEventType.GroupAdded,
        [MultipleChannelsViewed] = WebSocketEventType.MultipleChannelsViewed,
        [NewUser] = WebSocketEventType.NewUser,
        [UserAdded] = WebSocketEventType.UserAdded,
        [UserUpdated] = WebSocketEventType.UserUpdated,
        [UserRemoved] = WebSocketEventType.UserRemoved,
        [UserRoleUpdated] = WebSocketEventType.UserRoleUpdated,
        [MemberRoleUpdated] = WebSocketEventType.MemberRoleUpdated,
        [UserActivationStatusChange] = WebSocketEventType.UserActivationStatusChange,
        [Typing] = WebSocketEventType.Typing,
        [StatusChange] = WebSocketEventType.StatusChange,
        [PresenceIndicator] = WebSocketEventType.PresenceIndicator,
        [AddedToTeam] = WebSocketEventType.AddedToTeam,
        [LeaveTeam] = WebSocketEventType.LeaveTeam,
        [UpdateTeam] = WebSocketEventType.UpdateTeam,
        [DeleteTeam] = WebSocketEventType.DeleteTeam,
        [RestoreTeam] = WebSocketEventType.RestoreTeam,
        [UpdateTeamScheme] = WebSocketEventType.UpdateTeamScheme,
        [ThreadUpdated] = WebSocketEventType.ThreadUpdated,
        [ThreadFollowChanged] = WebSocketEventType.ThreadFollowChanged,
        [ThreadReadChanged] = WebSocketEventType.ThreadReadChanged,
        [PreferencesChanged] = WebSocketEventType.PreferencesChanged,
        [PreferencesDeleted] = WebSocketEventType.PreferencesDeleted,
        [EmojiAdded] = WebSocketEventType.EmojiAdded,
        [SidebarCategoryCreated] = WebSocketEventType.SidebarCategoryCreated,
        [SidebarCategoryUpdated] = WebSocketEventType.SidebarCategoryUpdated,
        [SidebarCategoryDeleted] = WebSocketEventType.SidebarCategoryDeleted,
        [SidebarCategoryOrderUpdated] = WebSocketEventType.SidebarCategoryOrderUpdated,
        [RoleUpdated] = WebSocketEventType.RoleUpdated,
        [PluginStatusesChanged] = WebSocketEventType.PluginStatusesChanged,
        [PluginEnabled] = WebSocketEventType.PluginEnabled,
        [PluginDisabled] = WebSocketEventType.PluginDisabled,
        [LicenseChanged] = WebSocketEventType.LicenseChanged,
        [ConfigChanged] = WebSocketEventType.ConfigChanged,
        [OpenDialog] = WebSocketEventType.OpenDialog,
        [CloseDialog] = WebSocketEventType.CloseDialog,
        [DraftCreated] = WebSocketEventType.DraftCreated,
        [DraftUpdated] = WebSocketEventType.DraftUpdated,
        [DraftDeleted] = WebSocketEventType.DraftDeleted,
        [CallStarted] = WebSocketEventType.CallStarted,
        [CallEnded] = WebSocketEventType.CallEnded,
        [CallUserJoined] = WebSocketEventType.CallUserJoined,
        [CallUserLeft] = WebSocketEventType.CallUserLeft,
        [CallScreenOn] = WebSocketEventType.CallScreenOn,
        [CallScreenOff] = WebSocketEventType.CallScreenOff,
        [CallChannelState] = WebSocketEventType.CallChannelState,
        [ReceivedGroup] = WebSocketEventType.ReceivedGroup,
        [ReceivedGroupAssociatedToTeam] = WebSocketEventType.ReceivedGroupAssociatedToTeam,
        [ReceivedGroupNotAssociatedToTeam] = WebSocketEventType.ReceivedGroupNotAssociatedToTeam,
        [ReceivedGroupAssociatedToChannel] = WebSocketEventType.ReceivedGroupAssociatedToChannel,
        [ReceivedGroupNotAssociatedToChannel] = WebSocketEventType.ReceivedGroupNotAssociatedToChannel,
        [GroupMemberAdd] = WebSocketEventType.GroupMemberAdd,
        [GroupMemberDelete] = WebSocketEventType.GroupMemberDelete,
        [CloudPaymentStatusUpdated] = WebSocketEventType.CloudPaymentStatusUpdated,
        [CloudSubscriptionChanged] = WebSocketEventType.CloudSubscriptionChanged,
        [ChannelBookmarkCreated] = WebSocketEventType.ChannelBookmarkCreated,
        [ChannelBookmarkUpdated] = WebSocketEventType.ChannelBookmarkUpdated,
        [ChannelBookmarkDeleted] = WebSocketEventType.ChannelBookmarkDeleted,
        [ChannelBookmarkSorted] = WebSocketEventType.ChannelBookmarkSorted,
        [ScheduledPostCreated] = WebSocketEventType.ScheduledPostCreated,
        [ScheduledPostUpdated] = WebSocketEventType.ScheduledPostUpdated,
        [ScheduledPostDeleted] = WebSocketEventType.ScheduledPostDeleted,
        [GuestRequested] = WebSocketEventType.GuestRequested,
        [PostTranslationUpdated] = WebSocketEventType.PostTranslationUpdated,
        [ShowToast] = WebSocketEventType.ShowToast,
        [WebRTC] = WebSocketEventType.WebRTC,
    };

    public static WebSocketEventType Parse(string? eventName)
    {
        if (eventName is null) return WebSocketEventType.Unknown;
        return NameToType.TryGetValue(eventName, out var type) ? type : WebSocketEventType.Unknown;
    }
}
